=== VitaliiKalinchyk/topic08/input.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--  XML schema -->

<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
            targetNamespace="http://com.epam.rd.java.basic.topic08"
            xmlns:tns="http://com.epam.rd.java.basic.topic08">

    <xsd:element name="exchange" type="tns:exchange_type"/>
    <xsd:complexType name="exchange_type">
        <xsd:sequence>
            <xsd:element name="currency" type="tns:currency_type" maxOccurs="unbounded"/>
        </xsd:sequence>
    </xsd:complexType>
    <xsd:complexType name="currency_type">
        <xsd:sequence>
            <xsd:element name="id" type="xsd:int"/>
            <xsd:element name="name" type="xsd:string"/>
            <xsd:element name="rate" type="xsd:double"/>
            <xsd:element name="abr" type="xsd:string"/>
        </xsd:sequence>
    </xsd:complexType>
</xsd:schema>

=== VitaliiKalinchyk/topic08/input.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--  Input XML document. This XML is valid against Test.xsd XML schema-->

<tn:exchange xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		xsi:schemaLocation="http://com.epam.rd.java.basic.topic08 input.xsd"
		xmlns:tn="http://com.epam.rd.java.basic.topic08">

	<currency>
		<id>36</id>
		<name>Австралійський долар</name>
		<rate>23.4844</rate>
		<abr>AUD</abr>
	</currency>
	<currency>
		<id>124</id>
		<name>Канадський долар</name>
		<rate>26.8818</rate>
		<abr>CAD</abr>
	</currency>
	<currency>
		<id>156</id>
		<name>Юань Женьміньбі</name>
		<rate>5.0214</rate>
		<abr>CNY</abr>
	</currency>
	<currency>
		<id>191</id>
		<name>Куна</name>
		<rate>4.7278</rate>
		<abr>HRK</abr>
	</currency>
	<currency>
		<id>203</id>
		<name>Чеська крона</name>
		<rate>1.452</rate>
		<abr>CZK</abr>
	</currency>
	<currency>
		<id>208</id>
		<name>Данська крона</name>
		<rate>4.7867</rate>
		<abr>DKK</abr>
	</currency>

</tn:exchange>
